TrajectoryPlannerROS:

  max_vel_x: 0.45
  min_vel_x: 0.1
  max_vel_theta: 0.15
min_vel_theta: -0.15
min_in_place_rotational_vel: 0.01
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

#computes velocity commands to send to robot