obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: 
	{sensor_frame: base_link, 
	observation_persistence: 0.0,
	max_obstacle_height: 0.4, 
	min_obstacle_height: 0.0
	data_type: LaserScan, 
	topic: scan, 
	marking: true, 
	clearing: true}

#cost_scaling_factor: 10.0
#map_topic: /map
#subscribe_to_updates: true
#global_frame: map
#robot_base_frame: base_link
#always_send_full_costmap: true