global_costmap:
	global_frame: /map
	robot_base_frame: base_link
	update_frequency: 5.0
	static_map: false

  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.1 
publish_frequency: 5.0
  transform_tolerance: 0.5
  width: 15
  height: 15
  origin_x: -7.5
  origin_y: -7.5